# Generated by Django 4.0 on 2022-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0004_alter_image_landimage_alter_image_squareimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
